### ISSUE TITLE
关于mobileSelect.js报错的问题

### ISSUE THREAD

**Issue by lqh21** [onlyhom/mobileSelect.js#1]
你好，我是根据readme提示，引入了css&js，然后报错，如下
`Uncaught TypeError: Cannot set property 'readOnly' of null
    at MobileSelect.init (mobileSelect.js:49)
    at new MobileSelect (mobileSelect.js:27)
    at ins_car_owner.html:112`
请问这个问题的原因是什么，怎么解决这个问题

**Comment by onlyhom** [comment]
你好~ 请问你有按这样的格式实例化吗




```html
<script type="text/javascript">
var mobileSelect1 = new MobileSelect({
    trigger: '#day', 
    title: '单项选择',  
    wheels: [
                {data:['周日','周一','周二','周三','周四','周五','周六']}
            ],
    position:[2] //初始化定位
});
</script>
```


trigger的值 是你html中一个input标签的id  
你的报错信息的意思是 js不能给一个空对象设置 “readOnly“ 只读属性  会不会是你页面中没有一个这样的input标签 或者没有给他设置id呢   
因为这个input专门用存储选择信息 不能让用户去手动输入去修改数值 所以要设置一个readOnly只读属性..
