### ISSUE TITLE
position初始化的值似乎并不正确

### ISSUE THREAD

**Issue by ChaseChan** [onlyhom/mobileSelect.js#13]
初始化的时候设置了position:[0,1]，发现只有位置变动了，但是数据没有更新。意思就是比如我的是地区选择联动的。然后设置position为[2,1],发现位置的确是移动到2,1了，但是2移动完毕的时候，并没有去更新数据，所以导致了这个bug，不知道新版的有没有修正这个问题呢？

**Comment by onlyhom** [comment]
你好~ 
你可以下载最新版，打开demo.html查看里面最后一个例子，
mobileSelect5 车型选择那一个，也是级联数据，修改初始化position的值，
试一试，看看还会不会遇到你所说的问题？
如果还有问题的话，欢迎继续告诉我，我再做修改

**Comment by ChaseChan** [comment]
问题已解决。
