### ISSUE TITLE
有一个小问题

### ISSUE THREAD

**Issue by ChaseChan** [onlyhom/mobileSelect.js#14]
您好，是这样的，初始化位置可以通过设置position，可以修改地区所在的位置。那如果这是一个订单页面，我就需要把callback的indexArr传递到下一个页面来做记录住当前的position。假如我不想用indexArr来，想用这种形式：广东省云浮市罗定市罗城镇 XX小山村。如果这么做的话，有两个问题，我不知道你的插件是否支持到多少级的联动，我也不知道从哪儿开始切这个数据，就算切完这个数据，然后遍历地区数据，那这个数据量会不会过于庞大。不知道作者有没有提供api让我去做这个事？

**Comment by ChaseChan** [comment]
是不是只有for循环地区数据，然后找出所在索引i，然后再赋值给position，这样初始化呢

**Comment by onlyhom** [comment]
你好~ 
这个是无限级联，多少级都支持。
嗯嗯是的，不用indexArr的话，就要遍历数据，找出索引i再赋值给position
（然后这样做的话，确实很耗性能。但是如果插件提供api的话，也是这么遍历循环你的数据找出索引的，也是一样的耗性能。所以还是建议把indexArr记录下来，传递过去。）

**Comment by ChaseChan** [comment]
好，那我就这样吧，谢谢作者，这是我用过的最炫的地址选择插件
