### ISSUE TITLE
例子中的仅仅保留第五个级联的在手机端触发不了，第一个单选的和第五个级联都保留的话，级联就可以用

### ISSUE THREAD

**Issue by guowangsheng** [onlyhom/mobileSelect.js#17]
试了下 只要单独一个使用都不可以，两个以上一起才可以

**Comment by onlyhom** [comment]
你好，我刚刚试了一下，删除了demo.html中前面四个例子，第五个可以正常使用。
你可以把你删除后的的代码贴上来，我看看是什么问题，还有就是你用什么浏览器打开的呢？

**Comment by guowangsheng** [comment]
.mobileSelect {
  position: relative;
  z-index: 0;
  opacity: 0;
  visibility: hidden;
  /* -webkit-transition: all 0.4s;
  transition: all 0.4s; */
}
把下面的这2个动画注释掉就可以了，IOS的钉钉扫码测试的

**Comment by onlyhom** [comment]
emmmm？？ 还有这种操作？  谢谢指正...  
我弄了个只剩例子5的测试网址  这个css没有做修改
[http://onlyhom.com/mobile-select2/demo.html]() 
刚刚用同事的IOS的钉钉打开测试了一下  好像没有问题  你也可以帮忙测试一下哈

**Comment by guowangsheng** [comment]
找到原因了，发现你的CSS和我的不一样，我的还是以前的版本，换成最新版本就可以了。thanks  
糗大了……

**Comment by onlyhom** [comment]
没事没事 和你交流很开森~
