### ISSUE TITLE
关于联动数据绑定的只能是有顺序的data-id

### ISSUE THREAD

**Issue by luckywangming** [onlyhom/mobileSelect.js#21]
当data-id是无序的时候 locatePostion()是无效的  不会自动去匹配到data-id去定位 该怎么解决呢

**Comment by onlyhom** [comment]
locatePosition()的参数是索引(就是你想要第几个显示在中间 就把索引填进去) 
它跟data-id的值是没有关系的，所以data-id是否无序并不重要
根据你的问题，有一个解决办法就是：
你循环遍历json数据源，例如：
```javascript
var index = 0;
for(var i=0; i++; i<data.length){
	if(data[i].id=='你指定的字符'){
		index = i;
		break;	
	}
}
```
把索引值index找出来，传进locatePosition()中去
