### ISSUE TITLE
与IScroll一起使用，点击不能弹出选择面板

### ISSUE THREAD

**Issue by spacecn** [onlyhom/mobileSelect.js#23]
与IScroll一起使用时，面板不能弹出，
经反复查看，是因为触发了两次点击事件，_this和_this.grayLayer，面板在弹出瞬间又关闭了。
解决方法1，改动源代码：
_this.trigger.addEventListener('click',function(){
    //_this.mobileSelect.classList.add('mobileSelect-show');
    setTimeout(function(){
        _this.mobileSelect.classList.add('mobileSelect-show');
    }, 20)
 });
解决方法2，改动源代码：
_this.grayLayer.addEventListener('click',function(){
    _this.mobileSelect.classList.remove('mobileSelect-show');
    _this.cancel(_this.curIndexArr, _this.curValue);
});
把“click”事件改为touchend

**Comment by onlyhom** [comment]
哇哦，谢谢你的答案
