### ISSUE TITLE
级联时使用 locatePosition() 方法更新选中值，轮子内的数据不会自动更新

### ISSUE THREAD

**Issue by huangxiuqi** [onlyhom/mobileSelect.js#26]
省市区三级联动，异步请求数据使用locatePosition() 更新选中时，轮子内的选项不会自动更新
现暂时修改了下locatePosition方法，可以正常更新了
locatePosition: function(index, posIndex){
    this.curDistance[index] = this.calcDistance(posIndex);
    this.movePosition(this.slider[index],this.curDistance[index]);
    var tempPosArr = this.getIndexArr();
    tempPosArr[index] = this.getIndex(this.curDistance[index]);
    this.checkRange(index, tempPosArr);
}

**Comment by onlyhom** [comment]
感谢你分享修改后的代码，这个项目原本只是非级联的，后来有了级联分类，这个函数就忘记优化了

``` javascript
	    locatePosition: function(index, posIndex){
	    	this.curDistance[index] = this.calcDistance(posIndex);
	    	this.movePosition(this.slider[index],this.curDistance[index]);
	        if(_this.cascade){
		        _this.checkRange(index, _this.getIndexArr());
		    }
	    },
```

这个是我修改后的，已更新。你提出这个问题之后，我发现我原来的程序里有冗余代码，已删减~ 
再次感谢，哈哈~
