### ISSUE TITLE
没有判断triggerDisplayData

### ISSUE THREAD

**Issue by andrewleeyou** [onlyhom/mobileSelect.js#27]
第86行，_this.trigger.innerHTML = tempValue;，这里你并没有根据triggerDisplayData的值来判断，加上一行判断即可：
if(config.triggerDisplayData!=false){
	_this.trigger.innerHTML = tempValue;
}

**Comment by onlyhom** [comment]
谢谢你的提问并做出了解答~
咦，但是我在第91行判断了，我刚测试了一下，设置为false时，
trigger里面的innerHTML是不会变的，难道是有兼容问题么0.0

**Comment by andrewleeyou** [comment]
我这里的代码并没有看到有判断，难道是因为是我下载的版本的问题吗？我是11月初下载的。

**Comment by onlyhom** [comment]
是在github上下载的吗？还是在别的插件网站下载的？

**Comment by andrewleeyou** [comment]
我第一次是在jq22上看到，并下载试后，正式用的版本我是在github上下的。。。咦。。。奇怪。。我重新下了个版本。在91行你确实有判断。。可能是我把别的网站上下载的版本和在github上下载的版本搞混乱了。。。sorry！哈哈。

**Comment by onlyhom** [comment]
hahaha好神奇... 没关系还是谢谢你hhh 
说到jq22我也是很桑心，jq22的mobileSelect不是我发布在上面的，是jq22的工作人员传上去的，我曾经在下面评论和投诉说上面的版本很古老，有很多bug，我说我是作者，希望由我本人维护，结果工作人员把我的留言删了，在github上重新下了一份，然后在介绍里面说，已更新到最新版...尴尬捂脸
不过他里面确实有很多好用的插件啦，还是一个很棒的网站，我以前也经常用hhh

**Comment by andrewleeyou** [comment]
嘿嘿。。加油！
