### ISSUE TITLE
城市数据格式

### ISSUE THREAD

**Issue by xilongxr** [onlyhom/mobileSelect.js#29]
楼主，你好，我的数据格式是这个样子的，有什么办法适应你的 插件
![json](https://user-images.githubusercontent.com/33031383/33561747-799c1eba-d94e-11e7-82ea-7096ac9a8176.png)

**Comment by onlyhom** [comment]
emmm... 因为你的数据格式里没有mobileSelect需要的键值，
插件暂时没办法适应你的数据格式，所以需要把你的数据格式改成：
var testData = [
    {
        id:'',
        value:'成都',
        childs:[
            {
                id:'',
                value:'锦江区',
                childs:[
                    {
                        id:'',
                        value:'监院街街道办事处'
                    },
                    {
                        id:'',
                        value:'盐市口街道办事处'
                    },
                    {
                        id:'',
                        value:'春熙路街道办事处'
                    }
                ]
            }
        ]
    }
];


var mobileSelect6 = new MobileSelect({
    trigger: '#trigger6',
    title: '测试',
    wheels: [
                {data : testData}
            ],
    transitionEnd:function(indexArr, data){
        console.log(data);
    },
    callback:function(indexArr, data){
        console.log(data);
    } 
});

如果你的数据是纯静态的数据，你一个一个改起来就比较麻烦，
如果是后台传给你的，可以让后台修改一下返回给你的格式。

**Comment by xilongxr** [comment]
非常感谢回复，好的，也只有这样了。之前用了 mint-ui 的picker，可以直接用下载的中国json数据做3级联动，楼主哪天心情好 可以改一改

**Comment by onlyhom** [comment]
好的~
