### ISSUE TITLE
点击2次才能启动

### ISSUE THREAD

**Issue by ifredom** [onlyhom/mobileSelect.js#3]
点击--触发函数showJigouList，点击2次才能启动，并且自动写如内容，应该取消自动写如。无法写如到指定位置。
function showJigouList(data){

			var mobileSelect1 = new MobileSelect({
//				['周日','周一','周二','周三','周四','周五','周六']
				trigger: '.showlist',
				title: '单项选择',
				wheels: [
					{data:list}
				],
				position:[2], //Initialize positioning
				callback:function(indexArr, data){
					console.log(JSON.stringify(data)); //Returns the selected json data
				}
			});

      	}

**Comment by yuwanfeng** [comment]
h5的移动端选择器  好用的并不多，加油维护啊，

**Comment by onlyhom** [comment]
你好~ 谢谢你的提问 ('◡')
我尝试着把你提供的代码测试了一下 并补全了一下 你看看是否和你的一致
```html
<div class="showlist" onclick="showJigouList()">测试</div>

<script type="text/javascript">
var list=['周日','周一','周二','周三','周四','周五','周六'];
function showJigouList(data){
	var mobileSelect1 = new MobileSelect({
		trigger: '.showlist',
		title: '单项选择',
		wheels: [
			{data:list}
		],
		position:[2], //Initialize positioning
		callback:function(indexArr, data){
			console.log(JSON.stringify(data)); //Returns the selected json data
		}
	});
}
</script>
```
①关于点击两次
我猜测你在trigger的div上使用了点击函数 
```html
<div class="showlist" onclick="showJigouList()">测试</div>
```
这样写是会点击两次才触发
你第一次点击 它执行的是你的showJigouList()函数 这个时候它才开始实例化
直到第二次点击以后 实例化完成的它才能开始响应trigger里的点击事件 并弹出控件 
同时 如果在点击函数里才实例化  这样又会导致一个问题
就是你每次点击 它都会实例化出一个新的对象
这样你点击100次 它就实例化出100个对象了 
所以建议不要在trigger上又添加一个点击函数 并且在函数里实例化

我不知道你需要实现怎样的效果...
如果需要点击弹出控件的话
是不需要另外写一个点击函数的
直接在初始化的参数trigger上填上一个div的id/class 就行了 
点击trigger 控件便会弹出了

②关于自动写入
如果你不想要这个div显示出你选择了什么
但是又想要一个区域供用户点击触发控件
可以设置这个div的opacity:0; 使透明值为0 

③写入到指定位置
这个你可以使用回调函数callback里返回的data 把数据写入到你想写的地方去
如果图方便 还可以把trigger的innerHTML(也可以用JQ的 $('').text())把选中的值取出来 
再把值写入到你想要的地方
