### ISSUE TITLE
点击选项触发的 transitionEnd 回调 返回的索引不正确

### ISSUE THREAD

**Issue by Myzhuzhijie** [onlyhom/mobileSelect.js#32]
点击选项先触发了touchend 事件，后触发了click事件。transitionEnd 回调拿到的索引总是上一次选中的选项的索引。
建议在click事件中再次调用transitionEnd 回调

addListenerLi 建议修改

MobileSelect.prototype.addListenerLi = function (sliderIndex) {
            var _this = this;
            var curWheelLi = _this.slider[sliderIndex].getElementsByTagName("li");
            for (var j = 0; j < curWheelLi.length; j++) {
                (function(j) {
                    curWheelLi[j].addEventListener("click",
                        function() {
                            _this.singleClick(this, j, sliderIndex);
                            _this.transitionEnd(_this.getIndexArr(), _this.getValue());
                        },
                        false);
                })(j);
            }
        }

**Comment by onlyhom** [comment]
感谢你建议及修改，已更正
