### ISSUE TITLE
多级联动，动态获取子级数据，用updateWheels更新数据，再用locatePosition定位后不能准确显示子级数据

### ISSUE THREAD

**Issue by Myzhuzhijie** [onlyhom/mobileSelect.js#33]
多级联动，动态获取子级数据，用updateWheels更新数据，再用locatePosition定位后不能准确显示子级数据。
用checkRange定位可以正常显示

**Comment by onlyhom** [comment]
您好，感谢你的issue，能麻烦展示一下您更新后的数据吗？
因为我根据您的描述，模拟了以下的数据，好像能够正常显示子集数据，可能是我模拟的不够准确。

``` html
<div id="trigger7">测试</div>
```

``` javascript
var mobileSelect7 = new MobileSelect({
    trigger: '#trigger7',
    title: '测试',
    wheels: [
                {data:[
                    {
                        id:'1',
                        value:'',
                        childs:[
                            {id:'',value:''},
                        ]
                    }
                ]}
            ],
    callback:function(indexArr, data){
        console.log(data);
    }
});


var afterData =
            [{
                id:'1',
                value:'更新后一级数据',
                childs:[
                    {
                        id:'',
                        value:'二级数据1'
                    },
                    {
                        id:'',
                        value:'二级数据2'
                    },
                    {
                        id:'',
                        value:'二级数据3',
                        childs: [
                            {
                                id:'',
                                value: '三级数据1',
                                childs:[
                                    {
                                        id:'',
                                        value: '四级数据1'
                                    },
                                    {
                                        id:'',
                                        value: '四级数据2'
                                    }
                                ]
                            },
                            {
                                id:'',
                                value: '三级数据2'
                            },
                            {
                                id:'',
                                value: '三级数据3'
                            }
                        ]
                    }
                ]
            }];

setTimeout(function(){
    mobileSelect7.updateWheels(afterData);
    mobileSelect7.locatePosition(0,0);
    mobileSelect7.locatePosition(1,2);
},1000);
```

**Comment by Myzhuzhijie** [comment]
var mobileSelect7 = new MobileSelect({
    trigger: '#trigger7',
    title: '异步填充数据测试',
    wheels: [
                {data:[
                    {
                        id:'1',
                        value:'',
                        childs:[
                            {id:'',value:''},
                        ]
                    },
                    {
                        id:'2',
                        value:'2',
                        childs:[
                            {id:'',value:''},
                        ]
                    }
                ]}
            ],
    callback:function(indexArr, data){
        console.log(data);
    }
});


var afterData =
            [{
                id:'1',
                value:'更新后一级数据',
                childs:[{Id:'',value:''}]
            },
          {
           id:'2',
value:'更新后的一级第二个选项',
childs:[
                    {
                        id:'',
                        value:'二级数据1'
                    },
                    {
                        id:'',
                        value:'二级数据2'
                    },
                    {
                        id:'',
                        value:'二级数据3',
                        childs: [
                            {
                                id:'',
                                value: '三级数据1',
                                childs:[
                                    {
                                        id:'',
                                        value: '四级数据1'
                                    },
                                    {
                                        id:'',
                                        value: '四级数据2'
                                    }
                                ]
                            },
                            {
                                id:'',
                                value: '三级数据2'
                            },
                            {
                                id:'',
                                value: '三级数据3'
                            }
                        ]
                    }
                ]
          }
];

setTimeout(function(){
    mobileSelect7.updateWheels(afterData);
    mobileSelect7.locatePosition(0,1);
    mobileSelect7.locatePosition(1,2);
},1000);


//试着模拟业务，选中一级的第二个选项，更新一级第二个选项的子级数据，再选中它。你就会发现我所描述的问题

**Comment by onlyhom** [comment]
按照您的描述，我这仍然可以检测到更新后的子级数据，根据您issue里说的用checkRange可以解决，
我猜想这个应该是以前老版本的bug，并在几个月以前已经解决。
您可以查看一下您下载的mobileSelect.js的541行的locatePosition()函数：
``` javascript
locatePosition: function(index, posIndex){
	var _this = this;
	this.curDistance[index] = this.calcDistance(posIndex);
	this.movePosition(this.slider[index],this.curDistance[index]);
	if(_this.cascade){ 
		_this.checkRange(index, _this.getIndexArr());  // 如果没有这一语句，则说明是以前的老版本
	}
},
```

**Comment by Myzhuzhijie** [comment]
果然是老版本
