### ISSUE TITLE
请教，如何可以实现按下选下中间的部分来确认？

### ISSUE THREAD

**Issue by darkorcale** [onlyhom/mobileSelect.js#34]
您好，

我想请问一下在iOS里，可以按下选项中间被选择部分来得到确认，

怎样可以mobileSelect.js里实现使按下诸如"select Line“的部分来得到同样结果？

**Comment by onlyhom** [comment]
我用ios的 
``` html
<input type="date"> 
```
试了一下，并不可以用中间的部分来确认，不知您是在哪里看到的？

这个功能以前我也有想过，可从selectLine入手，但我当时没能研究出结果：
首先，我给的selectLine加了一个css属性：pointer-events: none;
这个属性是为了解决穿透问题：不让selectLine 监听到任何事件，从而让下面的轮子元素获得监听事件。
如果需要实现点击中间这个区域完成选择事件，为selectLine添加监听事件，就会产生矛盾。
所以您可以研究一下是否能去掉pointer-events: none;属性，让selectLine可监听事件，同时又不会遮挡轮子监听函数，（不知是否与事件传递有关）。
再者可以从selectContainer的css属性考虑，但会计算上比较麻烦：translate3d()里的y轴的位置入手，
根据当前translate3d()的y轴数值占整个selectContainer的位置计算出当前哪一个选项处于屏幕中间，在singleClick()函数中进行判断，如果是当前选中，则调用选择完成的函数。

**Comment by darkorcale** [comment]
感谢您的答复

首先，我误认了iOS的举动，的确不可以用中间部分来确认。

但我的同事建议如果点击中间来可以得到确认的话，
可以让用户有更好的体验。所以提出了这个问题。

我会试试去掉pointer-events: none;牺牲滑轮中间的滚动监听
来换取中间部分selectLine的监听。比较一下体验效果。

再次感谢您的指点
