### ISSUE TITLE
安卓4.4.2/4.4.4系统，目前发现oppo 华为等手机会报错

### ISSUE THREAD

**Issue by HK8383** [onlyhom/mobileSelect.js#36]
我使用的是插件1.0.9版本,报错行数为540行，是updateCurDistance这个方法，报错内容为Cannot call method ‘split’ of undefined。应该是滑动的时候报的错误，在这种低版本安卓机型中，几乎没法滑动，或者滑动很卡顿，很难定位。不过可以点击选项一步步下拉。希望大神做下兼容。

**Comment by onlyhom** [comment]
emmm...我身边没有低版本的安卓机可以测试&debug，
在网上找了个4.4.2的华为Mate7云真机测试，好像没什么问题。
看了一下您说报错的地方，应该是低版本不兼容css中的transform，现已在js中增加-webkit-前缀(webkitTransform)，请更新到1.0.11版本使用。
