### ISSUE TITLE
liHight 为 0，导致计算错误问题

### ISSUE THREAD

**Issue by sevencai** [onlyhom/mobileSelect.js#38]
如果一开始组件为 display: none，

开发者在页面加载就初始化了 new MobileSelect(config)，但是此时组件为 display: none, 

那么这个时候因为是在 new 里进行的计算 li 高度， 就会导致 li 的 offsetHight 就为 0，导致报错。

这里最好更改为在点击 确认查询的时候，如果 liHeight 为 0，就再计算一次。

```
_this.ensureBtn.addEventListener('click',function(){
    _this.hide();

    if(!_this.liHeight) {
          _this.liHeight =  _this.mobileSelect.querySelector('li').offsetHeight;
    }
}

```

这样可以避免在后面计算 index 的时候，由于 this.liHeight 为 0，导致了 return 回来的值为 infinity 的现象。
```
getIndex: function(distance){
   return Math.round((2*this.liHeight-distance)/this.liHeight);
},
```

**Comment by onlyhom** [comment]
非常感谢指出，已更正~
