### ISSUE TITLE
建议增加 click 事件开关, 

### ISSUE THREAD

**Issue by aaalog** [onlyhom/mobileSelect.js#39]
如果是 click 操作, 将会分别触发 touchend 和 click 事件, 
touchend 回调返回的是改变之前的数据,
click 回调返回的是改变后的最新数据,

建议 1
增加 click 事件开关, 如果不需要 click 事件 则可以自行传入配置来关掉 click 回调
例如: 
传入 isClickEvent: false 那么就不会触 click 事件

建议 2
给 transitionEnd 回调传入第三个参数 types, 
用于区分当前回调是由 touchend 还是 click 触发

**Comment by onlyhom** [comment]
非常感觉你的建议，给我的修改提供了思路
根据您提出的 ”如果是 click 操作, 将会分别触发 touchend 和 click 事件“，
我更改了click的写法：
去除了click的监听，
直接判断touchend的位置是否等于touchstart的位置，来确定是否为单击事件，
这样既实现了单击移动的功能，也实现了transitionEnd()只会被触发一次。
代码已更新，请重新下载最新版使用
