### ISSUE TITLE
一个页面有多个选择框的时候updateWheel()不知道怎么使用

### ISSUE THREAD

**Issue by li362692680** [onlyhom/mobileSelect.js#4]
一个页面有多个选择框的时候updateWheel()不知道怎么使用，不知道要怎么定位到我要更新的MobileSelect

**Comment by SnowChasm** [comment]
你原来初始化的时候，用了 var XXX01  = new MobileSelect ...... ,  
                                           var XXX02 = new MobileSelect ...... 
根据你定义的变量（就是XXX01或者XXX02）来定位你要更新的select

**Comment by li362692680** [comment]
你说的这种情况适合于选择框固定的情况，我的应用场景选择框是循环拼装的，个数不确定，内容也不确定。建议可以根据trigger获取到选择框对象。 @SnowChasm
