### ISSUE TITLE
vue点击事件下重复创建，mounted下报错

### ISSUE THREAD

**Issue by hmfng** [onlyhom/mobileSelect.js#41]
在vue下使用：
问题1：在某个dom元素中使用@click=“doSth”,在doSth下new Mobile() 会重复创建。
问题2：在mounted下使用报错，错误原因：Error in mounted hook: "TypeError: Cannot read property 'offsetHeight' of null"

**Comment by onlyhom** [comment]
关于问题一：
不知为何您要这样写，为何每点击一次就实例化？
如果您是需要实现点击某个dom就弹出组件，建议使用show()、hide()方法
用法如：
```javascript
mobileSelect1.show(); //显示组件
mobileSelect1.hide(); //隐藏组件
```
关于问题二：
我之前在vue的mounted下使用过，没有出现问题
您目前给出的条件不足，无法定位到错误

**Comment by hmfng** [comment]
呃。先谢谢你这么耐心
其次，抱个歉。怪我逻辑没理清楚就发个issue
最后重新描述一下昨天遇到的问题。
我在mounted下new Mobile()，报错Error in mounted hook: "TypeError: Cannot read property 'offsetHeight' of null"。没多想，直接放在@click="doSth"，下点击触发。
为什么这么想是因为我感觉这个插件应该是创建用完了之后就销毁，所以直接放在点击事件下。

今天重新试了一下，找到原因了，如下：
我的数据是从后台接口调的，如果调用失败，就意味着没数据，那么data就是个空null，就会报我上面的错误Cannot read property 'offsetHeight' of null。

所以插件的参数wheels: [{data: ? }]这里是否应该给一个默认值？

**Comment by onlyhom** [comment]
如果需要异步加载数据，请确保数据已存在，再进行实例化（写在ajax的success里或其他，还要判断data是否为空以及data长度是否大于零），因为没有数据的话，就算弹出组件，用户也没有东西可以选择
wheels: [{data: ? }] 这里是必填参数，如果需要默认值，您可以自己设一个默认值，例如：
```javascript
//此处默认值例子为联动数据，非联动数据请查看文档
wheels: [ 
            {data:[
                {
                    id:'1',
                    value:'加载中',
                    childs:[
                        {id:'',value:'加载中'},
                    ]
                }
            ]}
        ],
```
获取数据成功后，再用mobileSelect1.updateWheels()，进行数据更新。
（联动数据使用updateWheels()，非联动数据使用updateWheel()，详细demo可阅读文档**功能函数**部分的**②ajax异步填充数据demo**）

最后感谢您的issue，我会在wheels数据为空时，打印错误信息，方便其他开发者调试。

**Comment by hmfng** [comment]
嗯，谢谢。学习了
给你的插件点赞。很好用

**Comment by onlyhom** [comment]
(*^▽^*)
